-- product_category_sales.sql
SELECT
    P.CATEGORY,
    SUM(F.ORDER_AMOUNT) AS CATEGORY_REVENUE
FROM ANALYTICS.FACT_ORDERS_CLEAN F
JOIN ANALYTICS.DIM_PRODUCTS P
    ON F.PRODUCT_ID = P.PRODUCT_ID
GROUP BY P.CATEGORY
ORDER BY CATEGORY_REVENUE DESC  